post http://localhost:5000/api/auth/register
Content-Type: application/json

{"username":"rom1",
"password":"rom",
"accType":"employee"}

###

post http://localhost:5000/api/auth/login
Content-Type: application/json

{
"username":"rom",
"password":"rom"
}